// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMLJ5J9fVBq9TQmLRicUUcQSW5tZEe-Y',
    appId: '1:115578057899:android:f68ba93260478676a773ee',
    messagingSenderId: '115578057899',
    projectId: 'tikgood',
    storageBucket: 'tikgood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZSow36nBuDONHcQCgg2oHCcErTIJlD8w',
    appId: '1:23633399985:ios:44eec838ed8c03e7779290',
    messagingSenderId: '23633399985',
    projectId: 'arabfinance-620a3',
    storageBucket: 'arabfinance-620a3.firebasestorage.app',
    androidClientId:
        '23633399985-2f3kkhp3ak41v9an91g4aq34f206rhrn.apps.googleusercontent.com',
    iosClientId:
        '23633399985-sh0eautm6hrki7i231pmpbslmda9bjlj.apps.googleusercontent.com',
    iosBundleId: 'af.securities.mobile_new',
  );
}